### ISSUE TITLE
Problem running lesson #4

### ISSUE THREAD

**Issue by fansari6** [smartcontractkit/full-blockchain-solidity-course-py#1312]
I am very new to all this and I am struck. I don't know how to proceed further. Please help.

I am unable to run "python deploy.py":
1. I am getting a squiggly red line under  pragma solidity >=0.6.0 <0.9.0; which I am unable to get rid of. I have tried everything mentioned in the video.
2. When I try to run python deploy.py, I get the error: INFO: Could not find files for the given pattern(s).

After struggling for several hours, I download lesson #4 and tried to run that. I get the following errors:

PS C:\Users\faruk\Desktop\web3_py_simple_storage-main> python deploy.py
INFO: Could not find files for the given pattern(s).
Installing...
Traceback (most recent call last):
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [WinError 10049] The requested address is not valid in its context

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\faruk\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\faruk\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\faruk\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\faruk\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1034, in _send_output
    self.send(msg)
  File "C:\Users\faruk\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 974, in send
    self.connect()
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001C8F582E910>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8F582E910>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\faruk\Desktop\web3_py_simple_storage-main\deploy.py", line 62, in <module>
    nonce = w3.eth.getTransactionCount(my_address)
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\web3\manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\web3\manager.py", line 150, in _make_request
    return request_func(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\web3\middleware\formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\web3\middleware\gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\web3\middleware\attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\web3\middleware\formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\web3\middleware\buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\web3\middleware\exception_retry_request.py", line 105, in middleware
    return make_request(method, params)
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\web3\providers\rpc.py", line 88, in make_request
    raw_response = make_post_request(
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\web3\_utils\request.py", line 48, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\faruk\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8F582E910>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))

**Comment by shashankvivek** [comment]
```
1. I am getting a squiggly red line under pragma solidity >=0.6.0 <0.9.0; which I am unable to get rid of. I have tried everything mentioned in the video.
> This would not impact anything even if you see the error. I started the course 5 days back and even with this error it works fine.

2. When I try to run python deploy.py, I get the error: INFO: Could not find files for the given pattern(s).
> This is not an error. It is an "INFO" . There are different level of logs. INFO is one of them. I am also getting this log message but the deploy.py works fine. Be patient and follow the steps. you'll be fine. Jumping over and "download lesson" direclty may not work as there are some files which you'll have to create on your local. 
```

**Comment by fansari6** [comment]
> 1. I am getting a squiggly red line under pragma solidity >=0.6.0 <0.9.0; which I am unable to get rid of. I have tried everything mentioned in the video.
> 
> > This would not impact anything even if you see the error. I started the course 5 days back and even with this error it works fine.
> 
> 2. When I try to run python deploy.py, I get the error: INFO: Could not find files for the given pattern(s).
> 
> > This is not an error. It is an "INFO" . There are different level of logs. INFO is one of them. I am also getting this log message but the deploy.py works fine. Be patient and follow the steps. you'll be fine. Jumping over and "download lesson" direclty may not work as there are some files which you'll have to create on your local.

Thank you!
