### ISSUE TITLE
Lesson3: Can't install web3 `pip install web3`

### ISSUE THREAD

**Issue by venturaEffect** [smartcontractkit/full-blockchain-solidity-course-py#1348]
Hi everyone

I came to an issue trying to install web3 and can't figure out why.

Here is the code:

   `zaesar@zaesar-X541UV:~/Escritorio/blockchain/demos/web3_py_simple_storage$ pip 
    install web3
    Defaulting to user installation because normal site-packages is not writeable
    Collecting web3
      Downloading web3-5.28.0-py3-none-any.whl (499 kB)            
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 499.6/499.6 KB 6.8 MB/s eta 0:00:00                                      
    Collecting eth-utils<2.0.0,>=1.9.5
      Downloading eth_utils-1.10.0-py3-none-any.whl (24 kB)
    Collecting lru-dict<2.0.0,>=1.1.6
      Downloading lru-dict-1.1.7.tar.gz (10 kB)
      Preparing metadata (setup.py) ... error
      error: subprocess-exited-with-error
  
      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [12 lines of output]
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 14, in <module>
            File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 14, in 
    <module>
              from setuptools.dist import Distribution, Feature
            File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 24, in <module>
              from setuptools.depends import Require
            File "/usr/lib/python3/dist-packages/setuptools/depends.py", line 7, in <module>
              from .py33compat import Bytecode
            File "/usr/lib/python3/dist-packages/setuptools/py33compat.py", line 54, in <module>
              unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
          AttributeError: 'HTMLParser' object has no attribute 'unescape'
          [end of output]
  
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed

    × Encountered error while generating package metadata.
    ╰─> See above for output.

    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.`

What is the problem and how can I solve it?

Appreciate your help!

**Comment by mebedel** [comment]
hey I found the solution
SIMPLE WAY TO INSTALL WEB3
Install irudict , cytools from [https://www.lfd.uci.edu/~gohlke/pythonlibs/](https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqbjY2QmU2WW9XZDZiMFFwc29BRGo3S0FyblVKd3xBQ3Jtc0tuNDF5WnVZTUh2RWdRT09FNGZtVDR3Z1hNSHNiZm9KMXVfTUtNanh1cVJzLUtXeHpEcXlTcElITjRSSnlZYmlRVE8xUVpoUmp6eW5hVVNaVjc0ZGg2dDZubFNZN3dFU1hENERiSWMyYmRydl9BUW81RQ&q=https%3A%2F%2Fwww.lfd.uci.edu%2F%7Egohlke%2Fpythonlibs%2F&stzid=UgwcMt1C-s_d8ZRRi8V4AaABAg)
watch this video [https://youtu.be/zbNczZLP1tA?t=348](https://www.youtube.com/watch?v=zbNczZLP1tA&t=348s)
if you don't know how to install from the wheels

Then paste: pip install bitarray==1.2.2 to cmd
after that pip install web3

It should work without needing to install visual c build tools
