### ISSUE TITLE
Chapter 4 web3 deploy issue

### ISSUE THREAD

**Issue by A-man-Pal** [smartcontractkit/full-blockchain-solidity-course-py#1413]
Used code :

from dis import Bytecode
import json
from web3 import Web3

# In the video, we forget to `install_solc`
# from solcx import compile_standard
from solcx import compile_standard, install_solc

with open("./SimpleStorage.sol", "r") as file:
    simple_storage_file = file.read()

# We add these two lines that we forgot from the video!

install_solc("0.6.0")

# Solidity source code
compiled_sol = compile_standard(
    {
        "language": "Solidity",
        "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
        "settings": {
            "outputSelection": {
                "*": {
                    "*": ["abi", "metadata", "evm.bytecode", "evm.bytecode.sourceMap"]
                }
            }
        },
    },
    solc_version="0.6.0",
)

with open("compiled_code.json", "w") as file:
    json.dump(compiled_sol, file)

# get the bytecode
bytecode = compiled_sol["contracts"]["SimpleStorage.sol"]["SimpleStorage"]["evm"][
    "bytecode"
]["object"]

# get abi
abi = compiled_sol["contracts"]["SimpleStorage.sol"]["SimpleStorage"]["abi"]

# for connecting to ganache
w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:7545"))
chain_id = 5777
my_address = "0x2CFF9E47A98c5c8cec7E41f800B4c65013f7602D"
private_key = "0x0e538ab6845a2934f68608bf90506b32fd9d14e91d5f340222239c1e86224918"

# Create the contract in python
SimpleStorage = w3.eth.contract(abi=abi, bytecode=bytecode)
# Get the latest transaction
nonce = w3.eth.getTransactionCount(my_address)
print(nonce)

# 1. Build a transaction
# 2. Sign a transaction
# 3. Send a transaction
transaction = SimpleStorage.constructor().buildTransaction(
    {"chainId": chain_id, "from": my_address, "nonce": nonce}
)
print(transaction)

---------------------------------------------------------------------------------------------------------------------------------------------------

Result i got after running this code:

0
Traceback (most recent call last):
  File "d:\VSCode\BlockChain\demos\web3_py_simple_storage\deploy.py", line 58, 
in <module>
    transaction = SimpleStorage.constructor().buildTransaction(
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\eth_utils\decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\contract.py", line 684, in buildTransaction
    return fill_transaction_defaults(self.web3, built_transaction)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__  
    return self.func(*args, **kwargs)
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\_utils\transactions.py", line 114, in fill_transaction_defaults
    default_val = default_getter(web3, transaction)
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\_utils\transactions.py", line 60, in <lambda>
    'gas': lambda web3, tx: web3.eth.estimate_gas(tx),
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\eth.py", line 868, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\manager.py", line 150, in _make_request
    return request_func(method, params)
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\formatting.py", line 93, in middleware
    params = formatter(params)
  File "cytoolz/functoolz.pyx", line 503, in cytoolz.functoolz.Compose.__call__    ret = PyObject_Call(self.first, args, kwargs)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__  
    return self.func(*args, **kwargs)
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\eth_utils\decorators.py", line 91, in wrapper
    return ReturnType(result)  # type: ignore
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\eth_utils\applicators.py", line 22, in apply_formatter_at_index
    yield formatter(item)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__  
    return self.func(*args, **kwargs)
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\eth_utils\functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\eth_utils\applicators.py", line 84, in apply_formatters_to_dict       
    yield key, formatters[key](item)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\eth_utils\applicators.py", line 72, in apply_formatter_if
    return formatter(value)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "C:\Users\amanp\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\validation.py", line 61, in _validate_chain_id        
    raise ValidationError(
web3.exceptions.ValidationError: The transaction declared chain ID 5777, but the connected node is on 1337
PS D:\VSCode\BlockChain\demos\web3_py_simple_storage> python -u "d:\VSCode\BlockChain\demos\web3_py_simple_storage\deploy.py"

---------------------------------------------------------------------------------------------------------------------------------------------------

I dont know what to do next like in video the output is different but here it looks failed code. It last line of output its written as connected node = 1337 which is of patrick (course instructor) but mine is 5777

**Comment by A-man-Pal** [comment]
i got the answer online its ganache clitch...
just change the network id in setting>server to 1337 and accordingly you will get new address and private key... Run it and everything will be fine...
