### ISSUE TITLE
Unable to install brownie

### ISSUE THREAD

**Issue by chinwan34** [smartcontractkit/full-blockchain-solidity-course-py#1469]
Hi,
It seems like my laptop have two versions of brownie installed at different locations.
I have downloaded using _**pipx install eth-brownie**_
<img width="919" alt="截圖 2022-05-08 21 28 22" src="https://user-images.githubusercontent.com/93521119/167314607-d3491b1b-98b4-4d11-9d0d-e4ee28d25c3a.png">
So apparently the brownie is created in: '/Users/roywan/.local/pipx/venvs/eth-brownie'.

However, when I attempted to type in _**brownie--version**_, the following happens:
- This shows that it is searching brownie in the path: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10

Error processing line 1 of /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sphinxcontrib_applehelp-1.0.2-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Error processing line 1 of /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sphinxcontrib_devhelp-1.0.2-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Error processing line 1 of /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sphinxcontrib_htmlhelp-2.0.0-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Error processing line 1 of /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sphinxcontrib_jsmath-1.0.1-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Error processing line 1 of /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sphinxcontrib_qthelp-1.0.3-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Error processing line 1 of /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sphinxcontrib_serializinghtml-1.1.5-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/brownie", line 33, in <module>
    sys.exit(load_entry_point('eth-brownie==1.18.1', 'console_scripts', 'brownie')())
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/brownie", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/eth_brownie-1.18.1-py3.10.egg/brownie/__init__.py", line 6, in <module>
    from brownie.project import compile_source, run
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/eth_brownie-1.18.1-py3.10.egg/brownie/project/__init__.py", line 3, in <module>
    from .main import (  # NOQA 401
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/eth_brownie-1.18.1-py3.10.egg/brownie/project/main.py", line 19, in <module>
    import requests
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/__init__.py", line 13, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 40, in <module>
    from .response import HTTPResponse
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 160, in <module>
    class HTTPResponse(io.IOBase):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/response.py", line 393, in HTTPResponse
    DECODER_ERROR_CLASSES += (brotli.error,)
AttributeError: module 'brotli' has no attribute 'error'

I would like to know how to solve this issue, as I really have no idea how to fix them. 
Thank you.

**Comment by chinwan34** [comment]
The image of the error when typing into terminal is as follows:
<img width="940" alt="截圖 2022-05-08 21 34 36" src="https://user-images.githubusercontent.com/93521119/167314837-3b8d2c1e-4b14-4727-93ac-7d54ab69132b.png">
<img width="938" alt="截圖 2022-05-08 21 35 00" src="https://user-images.githubusercontent.com/93521119/167314925-2824e709-9bf3-477f-986b-2a0ffc7d0bcd.png">
<img width="943" alt="截圖 2022-05-08 21 35 09" src="https://user-images.githubusercontent.com/93521119/167314935-174e96b9-b18c-4658-b879-7d639f552e12.png">
