### ISSUE TITLE
Lesson 4: requests.exceptions.InvalidSchema: No connection adapters were found for '127.0.0.1:8545'

### ISSUE THREAD

**Issue by juliab00** [smartcontractkit/full-blockchain-solidity-course-py#1515]
I have 2 questions

1.
because of the problem with "solcx" to run deploy.py script, I'm doing the following codes every time when I open a new terminal
# python3 -m venv env
# source env/bin/activate
# pip3 install py-solc-x

2. 
instead of yearn global add ganache-cli, as it didn't work for me, I had to npm install -g ganache-cli

and now I have 2 opened terminals 
one for "ganache-cli"
and one for run the deploy.py script, however, I got the following error and no idea where it comes from. I'm thinking of it maybe relevant to venv code I used? please let me know if there's any other solution for question 1

(env) (base) juliabae@Jooyoungs-Mac-mini web3_py_simple_storage % python deploy.py   
0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d
Traceback (most recent call last):
  File "/Users/juliabae/demos/web3_py_simple_storage/deploy.py", line 62, in <module>
    nonce = w3.eth.getTransactionCount(my_address)
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/web3/middleware/exception_retry_request.py", line 105, in middleware
    return make_request(method, params)
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/web3/providers/rpc.py", line 88, in make_request
    raw_response = make_post_request(
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/web3/_utils/request.py", line 102, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/requests/sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "/Users/juliabae/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/requests/sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '127.0.0.1:8545'

**Comment by raigal-r** [comment]
Hi, 
The first, no idea, The second I was having a similar error, related to the gas Price calculation. Check: https://stackoverflow.com/questions/72594258/userwarning-there-was-an-issue-with-the-method-eth-maxpriorityfeepergas-calcul
