### ISSUE TITLE
Solc problem from lesson 4. I keep getting this when i run the code using python deploy.py I'm using windows 10, don't know if that's the problem, please help i've been on this for 3 days. I've added this line: install_solc("0.6.0").

### ISSUE THREAD

**Issue by oloridama** [smartcontractkit/full-blockchain-solidity-course-py#1536]
Traceback (most recent call last):
File "C:\Users\3\demos\web3_py_simple_storage\deploy.py", line 6, in 
install_solc(_solc_version)
File "C:\Users\3\AppData\Local\Programs\Python\Python39\lib\site-packages\solcx\install.py", line 466, in install_solc
raise exc
File "C:\Users\3\AppData\Local\Programs\Python\Python39\lib\site-packages\solcx\install.py", line 459, in install_solc
_validate_installation(version, solcx_binary_path)
File "C:\Users\3\AppData\Local\Programs\Python\Python39\lib\site-packages\solcx\install.py", line 636, in _validate_installation
raise SolcInstallationError(
solcx.exceptions.SolcInstallationError: Downloaded binary would not execute, or returned unexpected output.

**Comment by taaha161** [comment]
having the same issue here. It worked fine on windows 8.1 but when i shifted to windows 10 it gives the same error

**Comment by oloridama** [comment]
> having the same issue here. It worked fine on windows 8.1 but when i shifted to windows 10 it gives the same error

Did you find a way around it? Cause I'm stuck, I may skip the lesson to lesson 5

**Comment by taaha161** [comment]
> > having the same issue here. It worked fine on windows 8.1 but when i shifted to windows 10 it gives the same error
> 
> Did you find a way around it? Cause I'm stuck, I may skip the lesson to lesson 5


Still haven't found a way around it. I dont think just skipping to lesson 5 would be a good idea because we cannot work with python if we cant install the solidity compiler. I wonder if someone could get Patrick to respond this

**Comment by oloridama** [comment]
> > > having the same issue here. It worked fine on windows 8.1 but when i shifted to windows 10 it gives the same error
> 
> > 
> 
> > Did you find a way around it? Cause I'm stuck, I may skip the lesson to lesson 5
> 
> 
> 
> 
> 
> Still haven't found a way around it. I dont think just skipping to lesson 5 would be a good idea because we cannot work with python if we cant install the solidity compiler. I wonder if someone could get Patrick to respond this
> 
> 
> 
> 

I just tagged him on Twitter, hopefully he'll take a look

**Comment by oloridama** [comment]
Problem solved by installing node.js and after which I ran in terminal "npm install -g solc" 
Code finally ran!!

**Comment by oloridama** [comment]
> Problem solved by installing node.js and after which I ran in terminal "npm install -g solc" Code finally ran!!

Download node.js for windows here
https://nodejs.org/en/

**Comment by taaha161** [comment]
> Problem solved by installing node.js and after which I ran in terminal "npm install -g solc" Code finally ran!!

FINALLY! You are a genius! I wonder what the issue was installing it with pip though?

**Comment by oloridama** [comment]
Yeah pip is a management system that installs packages written in python and found in python package index

**Comment by kriti0102** [comment]
I was having the same issue. I installed the solc compiler from npm. Did you add it somewhere in the brownie-config.yaml file?

**Comment by oloridama** [comment]
> I was having the same issue. I installed the solc compiler from npm. Did you add it somewhere in the brownie-config.yaml file? 

Nope! Didn't add to config. I just installed node.is first to my windows machine before installing solc globally from npm.

**Comment by kriti0102** [comment]
Ok so how did brownie which solc compiler to use?

**Comment by oloridama** [comment]
> Ok so how did brownie know which solc compiler to use?

Have you added this line to your deploy script? 
<code>from solcx import compile_standard, install_solc</code>

**Comment by oloridama** [comment]
> Ok so how did brownie know which solc compiler to use? 

Click <a href="https://github.com/PatrickAlphaC/web3_py_simple_storage/blob/main/deploy.py">here</a> to view the updated deploy script and compare with yours.
