### ISSUE TITLE
python deploy.py issue

### ISSUE THREAD

**Issue by Ruby-Newbie-85** [smartcontractkit/full-blockchain-solidity-course-py#1584]
PS C:\Users\wzuro\demos\web3_py_simple_storage> python deploy.py 
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "deploy.py", line 18, in <module>
    solc_version="0.6.0",
  File "C:\Users\wzuro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\solcx\main.py", line 371, in compile_standard     
    solc_binary = get_executable(solc_version)
  File "C:\Users\wzuro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\solcx\install.py", line 203, in get_executable    
    f"solc {version} has not been installed."
solcx.exceptions.SolcNotInstalled: solc 0.6.0 has not been installed. Use solcx.install_solc0.6.0 to install.

NOTE: Per the instructions in error message, i attempted to install soldiity 6.0 in terminal.  Also, some of the text i type into terminal is yellow in color. I can't seem to change version of python (bear in mind that I troubleshooted every suggestion listed on google)
ANY SUGGESTIONS ON HOW TO DEAL WITH THESE ISSUES WOULD BE MUCH APPRECIATED

**Comment by Mobey-eth** [comment]
install solidity version 0.6.0
