### ISSUE TITLE
Issue at Lesson 4: Signing the Transaction

### ISSUE THREAD

**Issue by MuhammadAwais0** [smartcontractkit/full-blockchain-solidity-course-py#1608]
So I have wrote everything correctly and checked by running the program till creating transaction, everything works fine but when i create the "sign_transaction" it gives error, and i can't seem to understand what it is about, let me copy paste it here.
The Error:
Traceback (most recent call last):
  File "/Users/madscientist/demos/web3_py_simpleStorage/deploy.py", line 61, in <module>
    signed_txn = w3.eth.account.sign_transaction(transaction, private_key=private_key)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/eth_account/account.py", line 748, in sign_transaction
    ) = sign_transaction_dict(account._key_obj, sanitized_transaction)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/eth_account/_utils/signing.py", line 32, in sign_transaction_dict
    unsigned_transaction = serializable_unsigned_transaction_from_dict(transaction_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/eth_account/_utils/legacy_transactions.py", line 42, in serializable_unsigned_transaction_from_dict
    return TypedTransaction.from_dict(transaction_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/eth_account/_utils/typed_transactions.py", line 145, in from_dict
    transaction=transaction.from_dict(dictionary),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/eth_account/_utils/typed_transactions.py", line 437, in from_dict
    cls.assert_valid_fields(dictionary)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/eth_account/_utils/typed_transactions.py", line 428, in assert_valid_fields
    raise TypeError("Transaction had invalid fields: %r" % invalid)
TypeError: Transaction had invalid fields: {'chainId': '1337'}

I have changed the chainId in ganache to 1337 but don't know the issue, here is my program:
from solcx import compile_standard
import json
from web3 import Web3
import os
from dotenv import load_dotenv

load_dotenv()

with open("./SimpleStorage.sol", "r") as file:
    simple_storage_file = file.read()

Compiled_sol = compile_standard(
    {
        "language": "Solidity",
        "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
        "settings": {
            "outputSelection": {
                "*": {"*": ["abi", "metadata", "evm.bytecode", "evm.sourceMap"]}
            }
        },
    },
    solc_version="0.6.0",
)
with open("compiled_code.json", "w") as file:
    json.dump(Compiled_sol, file)

    # get Bytecode
    bytecode = Compiled_sol["contracts"]["SimpleStorage.sol"]["simpleStorage"]["evm"][
        "bytecode"
    ]["object"]

    # get abi
    abi = Compiled_sol["contracts"]["SimpleStorage.sol"]["simpleStorage"]["abi"]

    # for collecting to Ganache
    w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:7545"))
    chain_id = "1337"
    my_address = "0x8A19205239d0711Db38a4887AB06457655D17F99"
    private_key = os.getenv("PK")
    # create the contract in python
    Simplestorage = w3.eth.contract(abi=abi, bytecode=bytecode)
    # get the nounce
    nonce = w3.eth.getTransactionCount(my_address)

    # 1: Build a Transaction
    # 2: Sign a Transaction
    # 3: Send a Transaction

    transaction = Simplestorage.constructor().buildTransaction(
        {
            "chainId": chain_id,
            "from": my_address,
            "nonce": nonce,
            "maxFeePerGas": 2000000000,
            "maxPriorityFeePerGas": 1000000000,
            "gasPrice": 20000000000,
            "gas": 6721975,
        }
    )
    signed_txn = w3.eth.account.sign_transaction(transaction, private_key=private_key)

**Comment by MuhammadAwais0** [comment]
so it was just a string/integer error, we aren't supposed to put chainid as a string. its solved now.
