### ISSUE TITLE
Lesson 4 : Ganache connection refused

### ISSUE THREAD

**Issue by ClearButton** [smartcontractkit/full-blockchain-solidity-course-py#1665]
Hi all,

I am stuck [at this stage of the video](https://youtu.be/M576WGiDBdQ?t=14320).
When running `python deploy.py`, the error below was raised.
I don't know how to correct it 😢 
I think it might be due to the fact that I am running my code in Ubuntu installed on WSL, but I installed Ganache directly on Windows.
If this is the issue, then how to install Ganache on WSL?

Thanks for your help!

<details>
<summary>Click here to see the error raised</summary>
<pre>
<code style="white-space:nowrap;">Traceback (most recent call last):
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/christian/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/christian/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/christian/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/christian/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/christian/.pyenv/versions/3.8.12/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fdc38e1bf40>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=7545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc38e1bf40>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deploy.py", line 49, in <module>
    nonce = w3.eth.getTransactionCount(my_address)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/web3/middleware/exception_retry_request.py", line 105, in middleware
    return make_request(method, params)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/web3/providers/rpc.py", line 88, in make_request
    raw_response = make_post_request(
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/web3/_utils/request.py", line 102, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/christian/.pyenv/versions/lewagon/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=7545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdc38e1bf40>: Failed to establish a new connection: [Errno 111] Connection refused'))</code>
</pre>
</details>

**Comment by ClearButton** [comment]
Hi,
I am back into the course, trying to solve my issue.
I still have the same problem... the line of code below generates the error:
`nonce = w3.eth.getTransactionCount(my_address)`

Anybody knows why?

**Comment by ClearButton** [comment]
ALLELUIA !

WSL users, go to this issue :
#1490
