### ISSUE TITLE
Lesson 4: solcx installation issue

### ISSUE THREAD

**Issue by MathisGreatCode** [smartcontractkit/full-blockchain-solidity-course-py#1682]
Hi everybody,
 After two days of trying to find the solution by myself, reading all related issues already posted here and in StackOverflow I'm asking for your help.
In lesson 4, I installed solcx as explained with "pip install py-solc-x", I have the message telling me it sucessfully installed but then when I'm trying to execute deploy.py typing "python deploy.py" in my terminal the following message appears:
(the first sentence is in French and means "unable to find files for the specified model(s).")

Information : impossible de trouver des fichiers pour le(s) modèle(s) spécifié(s).
Traceback (most recent call last):
  File "C:\Users\mathi\demos\web3_py_simple_storage\deploy.py", line 7, in <module>
    compiled_sol = compile_standard(
  File "C:\Users\mathi\AppData\Local\Programs\Python\Python310\lib\site-packages\solcx\main.py", line 371, in compile_standard
    solc_binary = get_executable(solc_version)
  File "C:\Users\mathi\AppData\Local\Programs\Python\Python310\lib\site-packages\solcx\install.py", line 183, in get_executable
    raise SolcNotInstalled(
solcx.exceptions.SolcNotInstalled: Solc is not installed. Call solcx.get_installable_solc_versions() to view for available versions and solcx.install_solc() to install.

I have tried many things but nothing worked, does anyone has a clue what should I do to make it work ?

**Comment by cromewar** [comment]
Hello @MathisGreatCode 
Try using python version 3.8 intead.
