### ISSUE TITLE
Lesson 5: Error in Installing Brownie

### ISSUE THREAD

**Issue by its-all-relative** [smartcontractkit/full-blockchain-solidity-course-py#1893]
Installing brownie has been a difficult task till now. 

Encountering multiple issues when installing brownie, both via pipx and via pip in venv. 

I have uninstalled and reinstalled all packages but not making progress in successfully installing Brownie when using studio code. Below is one of the many errors. Please advise. 

`Traceback (most recent call last):
  File "/Users/ishachandra/demos/brownie_simple_storage/brownie-env/bin/brownie", line 33, in <module>
    sys.exit(load_entry_point('eth-brownie==1.19.3', 'console_scripts', 'brownie')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishachandra/demos/brownie_simple_storage/brownie-env/bin/brownie", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ishachandra/demos/brownie_simple_storage/brownie-env/lib/python3.11/site-packages/eth_brownie-1.19.3-py3.11.egg/brownie/__init__.py", line 6, in <module>
    from brownie.project import compile_source, run
  File "/Users/ishachandra/demos/brownie_simple_storage/brownie-env/lib/python3.11/site-packages/eth_brownie-1.19.3-py3.11.egg/brownie/project/__init__.py", line 3, in <module>
    from .main import (  # NOQA 401
  File "/Users/ishachandra/demos/brownie_simple_storage/brownie-env/lib/python3.11/site-packages/eth_brownie-1.19.3-py3.11.egg/brownie/project/main.py", line 19, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
(brownie-env) Ishas-Air:brownie ishachandra$ brownie --version
Traceback (most recent call last):
  File "/Users/ishachandra/demos/brownie_simple_storage/brownie-env/bin/brownie", line 33, in <module>
    sys.exit(load_entry_point('eth-brownie==1.19.3', 'console_scripts', 'brownie')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishachandra/demos/brownie_simple_storage/brownie-env/bin/brownie", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ishachandra/demos/brownie_simple_storage/brownie-env/lib/python3.11/site-packages/eth_brownie-1.19.3-py3.11.egg/brownie/__init__.py", line 6, in <module>
    from brownie.project import compile_source, run
  File "/Users/ishachandra/demos/brownie_simple_storage/brownie-env/lib/python3.11/site-packages/eth_brownie-1.19.3-py3.11.egg/brownie/project/__init__.py", line 3, in <module>
    from .main import (  # NOQA 401
  File "/Users/ishachandra/demos/brownie_simple_storage/brownie-env/lib/python3.11/site-packages/eth_brownie-1.19.3-py3.11.egg/brownie/project/main.py", line 19, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

**Comment by DS-Coding0** [comment]
Try

pip install requests
pip install cytoolz

and after that try to install brownie again, but in Lesson 6 you come to an end... because there are some libraries that doesn't work anymore i think.

Had try different Python Versions but it doesn't work for me.
