### ISSUE TITLE
Lesson 4: Error with solcx

### ISSUE THREAD

**Issue by anasimov** [smartcontractkit/full-blockchain-solidity-course-py#1903]
Hi, I've just started lesson 4 and I am having an issue. Running on mac.

Code:
```
from solcx import compile_standard, install_solc

with open("./SimpleStorage.sol", "r") as file:
    simple_storage_file = file.read()

compiled_sol = compile_standard(
    {
        "language": "Solidity",
        "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
        "settings": {
            "outputSelection": {
                "*": {"*": ["abi", "metadata", "evm.bytecode", "evm.sourceMap"]}
            }
        },
    },
    solc_version="0.6.0",
)
print(compiled_sol)
```
And here is the error:
```
Traceback (most recent call last):
  File "/Users/Corey/demos/web3_py_simple_storage/deploy.py", line 6, in <module>
    compiled_sol = compile_standard(
                   ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/solcx/main.py", line 347, in compile_standard
    solc_binary = get_executable(version=solc_version) if solc_binary is None else solc_binary
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/solcx/install.py", line 196, in get_executable
    raise SolcNotInstalled(
solcx.exceptions.SolcNotInstalled: solc 0.6.0 has not been installed. Use solcx.install_solc('0.6.0') to install.
```

**Comment by MarKiSS2000** [comment]
(What about this way?):


from solcx import compile_standard, install_solc

with open("./SimpleStorage.sol", "r") as file:
    simple_storage_file = file.read()
    
install_solc("0.6.0")
compiled_sol = compile_standard(
    {
        "language": "Solidity",
        "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
        "settings": {
            "outputSelection": {
                "*": {"*": ["abi", "metadata", "evm.bytecode", "evm.sourceMap"]}
            }
        },
    },
    solc_version="0.6.0",
)
print(compiled_sol)

**Comment by MarKiSS2000** [comment]
That is:
before the line 
"compiled_sol = compile_standard(" 
you add the line 
"install_solc("0.6.0")"

**Comment by MarKiSS2000** [comment]
That is:
before the line 
"compiled_sol = compile_standard(" 
you add the installation line 
"install_solc("0.6.0")"

**Comment by NobeyByte** [comment]
From some research of the py-solc-x repo, 
when py-solc-x implemented version 2, this broke something. Using version 1.1.1 should fix this.
The following commands in the correct python env / venv should resolve this issue:
`pip uninstall py-solc-x`
`pip install py-solc-x==1.1.1`

**Comment by Daniel-Anuooluwa** [comment]
It worked 

That is:
before the line
"compiled_sol = compile_standard("
you add the line
"install_solc("0.6.0")"

**Comment by emillysilva65** [comment]
It looks like the error indicates that solc version 0.6.0 hasn't been installed yet. After calling `install_solc("0.6.0")`, make sure you're running the code in the same environment where you're installing the Solidity compiler.
