### ISSUE TITLE
Import SimpleStorage from brownie 

### ISSUE THREAD

**Issue by GNMarques** [smartcontractkit/full-blockchain-solidity-course-py#222]
Hi,
I am getting this error when I try to import SimpleStorage from brownie.
Does anyone know how can I solve it

Launching 'ganache-cli.cmd --port 8545 --gasLimit 12000000 --accounts 10 --hardfork istanbul --mnemonic brownie'...
  File "C:\Users\gonca\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\_cli\run.py", line 49, in main
    return_value, frame = run(
  File "C:\Users\gonca\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\project\scripts.py", line 53, in run
    module = _import_from_path(script)
  File "C:\Users\gonca\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\project\scripts.py", line 149, in _import_from_path
    _import_cache[import_str] = importlib.import_module(import_str)
  File "C:\Users\gonca\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File ".\scripts\deploy.py", line 1, in <module>
    from brownie import accounts, config, SimpleStorage
ImportError: cannot import name 'SimpleStorage' from 'brownie' (C:\Users\gonca\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\__init__.py)
Terminating local RPC client...

**Comment by wb248860274** [comment]
> Line 5 in `contracts/SimpleStorage.sol`. Try to change the name of the contract:
> 
> _from_: `Simple_storage`
> 
> _to_: `SimpleStorage`


I have the same problem,I did that,but doesn't work.

![image](https://user-images.githubusercontent.com/35584596/155540074-5eea6e19-14c9-453d-b8c2-37f57abf05eb.png)
![image](https://user-images.githubusercontent.com/35584596/155540204-657da771-b654-43cd-879f-1069fd67b2e5.png)
![image](https://user-images.githubusercontent.com/35584596/155540340-93728785-e6b9-4a2f-a8d5-79958b0041c1.png)

**Comment by vsevdrob** [comment]
The `SimpleStorage.sol` isn’t there in `contracts` directory. I see it only in `build/contracts/`.

**Comment by wb248860274** [comment]
thank you very much

**Comment by harshuo2** [comment]
I have updated the contract name and also taken care that the .sol is not under build. I'm still getting this error
![image](https://user-images.githubusercontent.com/56684487/174353393-66e72ae8-e46c-474a-b7c9-5f7c625dda6f.png)
![image](https://user-images.githubusercontent.com/56684487/174353304-ba92d7a9-19d0-4be2-bafb-575b7a6f5908.png)
![image](https://user-images.githubusercontent.com/56684487/174353536-aaf5b860-ae2a-4cac-8d24-46a8c9fcde4d.png)

**Comment by Rsh125** [comment]
I am having the same issue, but for different, and unknown reasons. :(

PS C:\Users\rharl\demos\brownie_simple_storage> & C:/Python310/python.exe c:/Users/rharl/demos/brownie_simple_storage/tests/test_simple_storage.py
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "c:\Users\rharl\demos\brownie_simple_storage\tests\test_simple_storage.py", line 1, in <module>
    from brownie import SimpleStorage, accounts
ImportError: cannot import name 'SimpleStorage' from 'brownie' (C:\Users\rharl\AppData\Roaming\Python\Python310\site-packages\brownie\__init__.py)

**Script:**
from brownie import SimpleStorage, accounts

def test_deploy():
    # Arrange
    account = accounts[0]
    # Act
    simple_storage = SimpleStorage.deploy({"from": account})
    starting_value = simple_storage.retrieve()
    expected = 0
    # Assert
    assert starting_value == expected

**Contract:**
// SPDX-License-Identifier: MIT

pragma solidity >=0.6.0 <0.9.0;

contract SimpleStorage {
    uint256 favoriteNumber;

    // This is a comment!
    struct People {
        uint256 favoriteNumber;
        string name;
    }

    People[] public people;
    mapping(string => uint256) public nameToFavoriteNumber;

    function store(uint256 _favoriteNumber) public {
        favoriteNumber = _favoriteNumber;
    }

    function retrieve() public view returns (uint256) {
        return favoriteNumber;
    }

    function addPerson(string memory _name, uint256 _favoriteNumber) public {
        people.push(People(_favoriteNumber, _name));
        nameToFavoriteNumber[_name] = _favoriteNumber;
    }
}

**directory Layout:**

![image](https://user-images.githubusercontent.com/99621311/188508432-2ee536ab-8f4e-42a9-b954-4a9cf71feb39.png)

**Comment by nameless-codingman** [comment]
hello  i meet the same  problem ,but  my import name  the same as contract name  so  
i really dont  know what can i do ?
![image](https://user-images.githubusercontent.com/67813780/219074350-a372b245-4f94-4110-9a98-afd6db70a0ae.png)
![image](https://user-images.githubusercontent.com/67813780/219074519-87c691e6-e44c-4364-8fa5-9065feb103dc.png)

**Comment by 88vsd** [comment]
I see that the line 15 in `SimpleStorage.sol` gives a syntaxis error indication.

**Comment by nameless-codingman** [comment]
@88vsd  oh  that`s not  the point .......

**Comment by nameless-codingman** [comment]
@88vsd   ignore that ,so do you have any good idea to solve this question ?
please tell me  thanks very much ~~~~

**Comment by 88vsd** [comment]
Could you provide more info about the error displayed in console?

**Comment by nameless-codingman** [comment]
@88vsd ok  
![image](https://user-images.githubusercontent.com/67813780/219093265-f7c83fd6-7845-4f1f-a18c-aec0ea2f0ef0.png)

**Comment by 88vsd** [comment]
The contract should not be in folder `./build`. In general, this folder is not for manual modification. Normally, therein are locating by brownie generated files with the bytecode and ABI. 

What you can do:

1. Create a new file `SimpleStorage.sol` in `./contracts`
2. Copy the code from `./build/contracts/SimpleStorage.sol` to `./contracts/SimpleStorage.sol` and then save the file
3. Delete `./build` folder
4. Run `brownie run scripts/deploy.py` again

**Comment by nameless-codingman** [comment]
@88vsd  ok!!!  its work ! but my error message  has  changed  as you can see ,why the project  will report 'UnicodeDecodeError:'gbk' codec can't decode byte 0x80 in position 49: illegal multibyte sequence'   
![image](https://user-images.githubusercontent.com/67813780/219373665-1dad7e58-1f6b-4152-aee5-79a9e194025c.png)
my face like that pic
![image](https://user-images.githubusercontent.com/67813780/219374034-09cc047f-5c31-41e9-91e2-42fc55113fc8.png)

**Comment by yuvi189** [comment]
I believe im getting a similar error. I am not able to figure out how to fix the problem, any help please?
![image](https://github.com/smartcontractkit/full-blockchain-solidity-course-py/assets/99942096/32d05bdc-cd3d-4175-8561-47472eb14239)
