### ISSUE TITLE
Lesson 4 Issue: Transaction must not include unrecognized fields: {'chainID'}

### ISSUE THREAD

**Issue by cassandriadb** [smartcontractkit/full-blockchain-solidity-course-py#394]
I am stuck at lesson 4 with an error when trying to print signed_txn

I am getting the following error:

```
Traceback (most recent call last):
  File "/Users/vickydevika/demos/web3_py_simple_storage/deploy.py", line 55, in <module>
    signed_txn = w3.eth.account.sign_transaction(transaction, private_key=private_key)
  File "/Users/vickydevika/demos/web3_py_simple_storage/venv/lib/python3.10/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/Users/vickydevika/demos/web3_py_simple_storage/venv/lib/python3.10/site-packages/eth_account/account.py", line 747, in sign_transaction
    ) = sign_transaction_dict(account._key_obj, sanitized_transaction)
  File "/Users/vickydevika/demos/web3_py_simple_storage/venv/lib/python3.10/site-packages/eth_account/_utils/signing.py", line 32, in sign_transaction_dict
    unsigned_transaction = serializable_unsigned_transaction_from_dict(transaction_dict)
  File "/Users/vickydevika/demos/web3_py_simple_storage/venv/lib/python3.10/site-packages/eth_account/_utils/legacy_transactions.py", line 44, in serializable_unsigned_transaction_from_dict
    assert_valid_fields(transaction_dict)
  File "/Users/vickydevika/demos/web3_py_simple_storage/venv/lib/python3.10/site-packages/eth_account/_utils/legacy_transactions.py", line 102, in assert_valid_fields
    raise TypeError("Transaction must not include unrecognized fields: %r" % superfluous_keys)
TypeError: Transaction must not include unrecognized fields: {'chainID'}
```

No problem whatsoever while printing transaction just before that.

Here's the full code from my deploy.py

````
from solcx import compile_standard, install_solc
import json
from web3 import Web3
import os
from dotenv import load_dotenv

load_dotenv()


install_solc("0.6.6")


with open("./SimpleStorage.sol", "r") as file:
    simple_storage_file = file.read()

compiled_sol = compile_standard(
    {
        "language": "Solidity",
        "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
        "settings": {
            "outputSelection": {
                "*": {"*": ["abi", "metadata", "evm.bytecode", "evm.sourceMap"]}
            }
        },
    },
    solc_version="0.6.6",
)
with open("compiled_code.json", "w") as file:
    json.dump(compiled_sol, file)


# get byte-code
bytecode = compiled_sol["contracts"]["SimpleStorage.sol"]["SimpleStorage"]["evm"][
    "bytecode"
]["object"]

# get abi
abi = compiled_sol["contracts"]["SimpleStorage.sol"]["SimpleStorage"]["abi"]

# for connecting
w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:7545"))
chain_id = 5777
my_address = "0xfAf934067643BD0714bC329f95fa55482ff4b605"
private_key = os.getenv("PRIVATE_KEY")
SimpleStorage = w3.eth.contract(abi=abi, bytecode=bytecode)

# Get the latest transaction

nonce = w3.eth.getTransactionCount(my_address)

transaction = SimpleStorage.constructor().buildTransaction(
    {"chainID": chain_id, "from": my_address, "nonce": nonce}
)

signed_txn = w3.eth.account.sign_transaction(transaction, private_key=private_key)
print(signed_txn)
```
Any help greatly appreciated, I'm really stuck.

**Comment by cassandriadb** [comment]
Also if I remove "chainID": chain_id from transaction, signed_txn prints properly. I'm a bit confused.

**Comment by cassandriadb** [comment]
found the solution, I typed chainID instead of chainId.

Silly me

**Comment by m1zr** [comment]
Also make sure to add gas price parameter like this:
`transaction = SimpleStorage.constructor().buildTransaction(
    {
        "chainId": chain_id,
        "gasPrice": w3.eth.gas_price,
        "from": my_address,
        "nonce": nonce,
    },
)`
