### ISSUE TITLE
Issue with brownie install

### ISSUE THREAD

**Issue by narainp** [smartcontractkit/full-blockchain-solidity-course-py#501]
Installed brownie and updated env variables:
python3 -m pip install --user pipx
python3 -m pipx ensurepath
pipx install eth-brownie
were successful.
 
But it seems the verification fails:

C:\brownie_simple_storage> brownie  
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\parik\.local\bin\brownie.exe\__main__.py", line 4, in <module>
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\__init__.py", line 6, in <module>
    from brownie.project import compile_source, run
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\project\__init__.py", line 3, in <module>
    from .main import (  # NOQA 401
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\project\main.py", line 41, in <module>
    from brownie.network import web3
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\__init__.py", line 4, in <module>
    from .account import Accounts
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\account.py", line 29, in <module>
    from .gas.bases import GasABC
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\gas\bases.py", line 7, in <module>
    from brownie.network.web3 import web3
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\web3.py", line 208, in <module>
    web3 = Web3()
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\web3.py", line 30, in __init__
    self.enable_unstable_package_management_api()
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\web3\main.py", line 289, in enable_unstable_package_management_api
    from web3.pm import PM  # noqa: F811
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\web3\pm.py", line 36, in <module>
    from ethpm import (
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\ethpm\__init__.py", line 8, in <module>
    from .package import Package  # noqa: F401
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\ethpm\package.py", line 60, in <module>
    from ethpm.uri import (
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\ethpm\uri.py", line 15, in <module>
    from ethpm._utils.backend import (
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\ethpm\_utils\backend.py", line 13, in <module>
    from ipfshttpclient.exceptions import (
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\ipfshttpclient\__init__.py", line 11, in <module>
    from .client import DEFAULT_ADDR, DEFAULT_BASE
    from . import bitswap
  File "C:\Users\parik\.local\pipx\venvs\eth-brownie\lib\site-packages\ipfshttpclient\client\bitswap.py", line 3, in <module>
    from . import base
    def returns_no_item(func: _inner_func_t[ty.NoReturn]) -> _returns_single_wrapper_t:
    return func(*args, **kwds)
  File "C:\Python37\lib\typing.py", line 824, in __class_getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "C:\Python37\lib\typing.py", line 824, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "C:\Python37\lib\typing.py", line 135, in _type_check
    raise TypeError(f"Plain {arg} is not valid as type argument")
TypeError: Plain typing.NoReturn is not valid as type argument

**Comment by cromewar** [comment]
Hello @narainp try installing brownie with pip instead pipx

**Comment by narainp** [comment]
>Thanks. Retried by following the steps again. Both using pip and pipx, everything seems to be installed without errors. But, the test fails still...

C:\brownie_simple_storage> brownie --version
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "C:\Python37\Scripts\brownie-script.py", line 33, in <module>
    sys.exit(load_entry_point('eth-brownie==1.17.2', 'console_scripts', 'brownie')())   
  File "C:\Python37\Scripts\brownie-script.py", line 25, in importlib_load_entry_point  
    return next(matches).load()
  File "C:\Python37\lib\site-packages\importlib_metadata\__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "C:\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Python37\lib\site-packages\brownie\__init__.py", line 6, in <module>
    from brownie.project import compile_source, run
  File "C:\Python37\lib\site-packages\brownie\project\__init__.py", line 3, in <module>
    from .main import (  # NOQA 401
  File "C:\Python37\lib\site-packages\brownie\project\main.py", line 41, in <module>
    from brownie.network import web3
  File "C:\Python37\lib\site-packages\brownie\network\__init__.py", line 4, in <module>
    from .account import Accounts
  File "C:\Python37\lib\site-packages\brownie\network\account.py", line 29, in <module>
    from .gas.bases import GasABC
  File "C:\Python37\lib\site-packages\brownie\network\gas\bases.py", line 7, in <module>
    from brownie.network.web3 import web3
  File "C:\Python37\lib\site-packages\brownie\network\web3.py", line 208, in <module>
    web3 = Web3()
  File "C:\Python37\lib\site-packages\brownie\network\web3.py", line 30, in __init__
    self.enable_unstable_package_management_api()
  File "c:\python37\lib\site-packages\web3-5.25.0-py3.7.egg\web3\main.py", line 356, in enable_unstable_package_management_api
    from web3.pm import PM  # noqa: F811
  File "c:\python37\lib\site-packages\web3-5.25.0-py3.7.egg\web3\pm.py", line 36, in <module>
    from ethpm import (
  File "c:\python37\lib\site-packages\web3-5.25.0-py3.7.egg\ethpm\__init__.py", line 19, in <module>
    from .package import Package  # noqa: E402, F401
  File "c:\python37\lib\site-packages\web3-5.25.0-py3.7.egg\ethpm\package.py", line 61, in <module>
    from ethpm.uri import (
  File "c:\python37\lib\site-packages\web3-5.25.0-py3.7.egg\ethpm\uri.py", line 18, in <module>
    from ethpm._utils.backend import (
  File "c:\python37\lib\site-packages\web3-5.25.0-py3.7.egg\ethpm\_utils\backend.py", line 13, in <module>
    from ipfshttpclient.exceptions import (
  File "c:\python37\lib\site-packages\ipfshttpclient-0.8.0a2-py3.7.egg\ipfshttpclient\__init__.py", line 11, in <module>
    from .client import DEFAULT_ADDR, \
  File "c:\python37\lib\site-packages\ipfshttpclient-0.8.0a2-py3.7.egg\ipfshttpclient\client\__init__.py", line 26, in <module>
    from . import base
  File "c:\python37\lib\site-packages\ipfshttpclient-0.8.0a2-py3.7.egg\ipfshttpclient\client\base.py", line 255, in <module>
    def returns_no_item(func: _inner_func_t[ty.NoReturn]) -> _returns_single_wrapper_t:
  File "C:\Python37\lib\typing.py", line 251, in inner
    return func(*args, **kwds)
  File "C:\Python37\lib\typing.py", line 824, in __class_getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "C:\Python37\lib\typing.py", line 824, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "C:\Python37\lib\typing.py", line 135, in _type_check
    raise TypeError(f"Plain {arg} is not valid as type argument")
TypeError: Plain typing.NoReturn is not valid as type argument

**Comment by cromewar** [comment]
It seems you have some conflicts with your python packages on windows, there is some steps that should help:

1. install visual studio and it's pythons development tools.
2. use python virtualenv (install it using pip), this allows you to to manage python virtual environments which independent libraries.
3. Use WSL (windows subsystem for linux) and manage all your python stuff there. (recommended)

I hope this info might work for you.
