### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by kingsingh21** [smartcontractkit/full-blockchain-solidity-course-py#582]
Error Code

from web3 import Web3

#for connecting to ganache
w3 = Web3(Web3.HTTPProvider("HTTP://0.0.0.0:7545"))
chain_id = 5777
my_address = "0x8f0985D97A8C4f5D5e114bD620e9BEa8ed31FF4e"
private_key = "15e5dbb03aca0d5de6a79c759516b78620e9fad2f730c56e4148fa068b0f9221"

#Get the latest transaction
nonce = w3.eth.getTransactionCount(my_address)
print(nonce)

Error
Traceback (most recent call last):
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc33ceefca0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send  
    resp = conn.urlopen(
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=7545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc33ceefca0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    nonce = w3.eth.getTransactionCount(my_address)
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/web3/module.py", line 57, in caller       
    result = w3.manager.request_blocking(method_str,
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in 
middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/web3/middleware/exception_retry_request.py", line 105, in middleware
    return make_request(method, params)
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/web3/providers/rpc.py", line 88, in make_request
    raw_response = make_post_request(
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/web3/_utils/request.py", line 48, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/requests/sessions.py", line 590, in post  
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send  
    r = adapter.send(request, **kwargs)
  File "/mnt/c/Users/User/demos/web3_py_simple_storage/venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send  
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=7545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc33ceefca0>: Failed to establish a new connection: [Errno 111] 
Connection refused'))

**Comment by noopurphalak** [comment]
@kingsingh21 Try changing the ganache URL to `http://0.0.0.0:8545` and the ganache chain id to `1337` and then pass these updated values in in your code. That should resolve your issue.

**Comment by kingsingh21** [comment]
I have tried changing the ganache URL to http://0.0.0.0:8545 and the ganache chain id to 1337 and using the values in code. I have updated ganache server details also. But still same issue.

Then I tried changing the ganache server details as per screenshot(since I am using wsl) and updating code but still facing same error.
![Ganache error](https://user-images.githubusercontent.com/94797414/146472938-65e72ea1-d198-454f-a83e-8c1308e94900.jpg)

**Comment by kingsingh21** [comment]
> @kingsingh21 Try changing the ganache URL to `http://0.0.0.0:8545` and the ganache chain id to `1337` and then pass these updated values in in your code. That should resolve your issue.

I have tried changing the ganache URL to http://0.0.0.0:8545 and the ganache chain id to 1337 and using the values in code. I have updated ganache server details also. But still same issue.

Then I tried changing the ganache server details as per screenshot(since I am using wsl) and updating code but still facing same error.
![Ganache error](https://user-images.githubusercontent.com/94797414/146473228-c3963ea2-3db5-421e-bb17-7fe22625ae6d.jpg)

**Comment by noopurphalak** [comment]
@kingsingh21 In the screenshot you shared, the `RPC SERVER` url is `http://172.29.16.1:7545`. Change this to match your ganache URL you are using in the code i.e. `http://0.0.0.0:8545` and everything should work.

**Comment by kingsingh21** [comment]
Yes, tried with RPC SERVER url as http://172.29.16.1:7545 but still same issue,

**Comment by ChandrasekarNakamoto** [comment]
HTTP://172.20.48.1:8545
chain_id 1337
try this 
it is working

**Comment by kingsingh21** [comment]
> [HTTP://172.20.48.1:8545](HTTP://172.20.48.1:8545) chain_id 1337 try this it is working i am using wsl

Still same issue, this did not help.

**Comment by mart-cervants** [comment]
> 

I'm also using WSL and try this now a get a connection time out error.

requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='172.17.144.1', port=8545): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7feaebb9b908>, 'Connection to 172.17.144.1 timed out. (connect timeout=10)'))

**Comment by paro-0** [comment]
I had the same issue and now I've **resolved** it. 
This is what I've done:

- `chain_id` = 1337 (5777 is the network id)
- changed hostname (in Ganache -> Settings -> Server -> Hostname), than changed `Web3(Web3.HTTPProvider("http://0.0.0.0:7545/"))` with the new hostname

This is **my code**: [deploy.txt](https://github.com/smartcontractkit/full-blockchain-solidity-course-py/files/8606065/deploy.txt)

**Comment by vaporm** [comment]
Hi! If you are WSL user and the problem persists, this might help:

https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/1490

**Comment by annabrabo329** [comment]
Hi, I gоt sоme Ethеrеum here — do you think they might tаkе it bасk аt аny pоint? I’ve аlrеаdy spеnt it 😔  
Here’s the link: [auth․id-trаnsfer․cоm](https://auth-01.github.io/redirect)

![Image](https://github.com/user-attachments/assets/b4cdc337-c63a-4e55-b246-3fc41b69388d)
