### ISSUE TITLE
Method eth_maxPriorityFeePerGas not supported

### ISSUE THREAD

**Issue by joeytheass** [smartcontractkit/full-blockchain-solidity-course-py#702]
Getting this error when building the transaction the first time at roughly 4:00:00 into the tutorial

Traceback (most recent call last):
  File "deploy.py", line 54, in <module>
    transaction = Storage.constructor().buildTransaction(
  File "/Users/j/Library/Python/3.8/lib/python/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/Users/j/Library/Python/3.8/lib/python/site-packages/web3/contract.py", line 684, in buildTransaction
    return fill_transaction_defaults(self.web3, built_transaction)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Users/j/Library/Python/3.8/lib/python/site-packages/web3/_utils/transactions.py", line 121, in fill_transaction_defaults
    default_val = default_getter(web3, transaction)
  File "/Users/j/Library/Python/3.8/lib/python/site-packages/web3/_utils/transactions.py", line 71, in <lambda>
    web3.eth.max_priority_fee + (2 * web3.eth.get_block('latest')['baseFeePerGas'])
  File "/Users/j/Library/Python/3.8/lib/python/site-packages/web3/eth.py", line 549, in max_priority_fee
    return self._max_priority_fee()
  File "/Users/j/Library/Python/3.8/lib/python/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/Users/j/Library/Python/3.8/lib/python/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/Users/j/Library/Python/3.8/lib/python/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'message': 'Method eth_maxPriorityFeePerGas not supported.', 'code': -32000, 'data': {'stack': 'Error: Method eth_maxPriorityFeePerGas not supported.\n    at GethApiDouble.handleRequest (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/subproviders/geth_api_double.js:70:16)\n    at next (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at GethDefaults.handleRequest (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/subproviders/gethdefaults.js:15:12)\n    at next (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at SubscriptionSubprovider.FilterSubprovider.handleRequest (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/filters.js:89:7)\n    at SubscriptionSubprovider.handleRequest (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:137:49)\n    at next (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at DelayedBlockFilter.handleRequest (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/subproviders/delayedblockfilter.js:31:3)\n    at next (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at RequestFunnel.handleRequest (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/subproviders/requestfunnel.js:32:12)\n    at next (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at Web3ProviderEngine._handleAsync (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:123:3)\n    at Timeout._onTimeout (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:107:12)\n    at listOnTimeout (internal/timers.js:531:17)\n    at processTimers (internal/timers.js:475:7)', 'name': 'Error'}}

**Comment by joeytheass** [comment]
deploy.py
```
from solcx import compile_standard, install_solc
import json
from web3 import Web3

install_solc("0.6.6")

with open("./Storage.sol", "r") as file:
    storage_file = file.read()
    print(storage_file)

# Compile the Solidiy Code
compiled_sol = compile_standard(
    {
        "language": "Solidity",
        "sources": {"Storage.sol": {"content": storage_file}},
        "settings": {
            "outputSelection": {
                "*": {"*": ["abi", "metadata", "evm.bytecode", "evm.sourceMap"]}
            }
        },
    },
    solc_version="0.6.6",
)

with open("compiled_code.json", "w") as file:
    json.dump(compiled_sol, file)

# get bytecode
bytecode = compiled_sol["contracts"]["Storage.sol"]["Storage"]["evm"]["bytecode"][
    "object"
]
# get ABI
abi = compiled_sol["contracts"]["Storage.sol"]["Storage"]["abi"]

# For connecting to ganache
w3 = Web3(Web3.HTTPProvider("http://0.0.0.0:7545"))
chain_id = 1337
my_address = "0x4bd7cD8F349A832AB75a92Ac9Bb0DB08d27D5A86"
private_key = "7bff858e8179ab40091fbf93a7d948dffe80e8ce51d5320a3e47a7f32b41881e"

# Create the contract in python

Storage = w3.eth.contract(abi=abi, bytecode=bytecode)
print(Storage)

# Get Latest transaction count for nonce

nonce = w3.eth.getTransactionCount(my_address)
print(nonce)

# 1. Build a transaction
# 2. Sign a transaction
# 3. Send a transaction
transaction = Storage.constructor().buildTransaction(
    {"chainId": chain_id, "from": my_address, "nonce": nonce}
)

print(transaction)

```
Storage.sol

```
//SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

contract Storage {
    //creates balance
    uint256 public balance;
    //defines Accounts structure
    struct Accounts {
        string name;
        uint256 balance;
    }
    //Generates Array of accounts
    Accounts[] public accounts;

    //Creates mapping for accounts
    mapping(string => uint256) public nameToBalance;

    //stores balance values
    function store(uint256 _balance) public {
        balance = _balance;
    }

    //retrieves balance value
    function retrieve() public view returns (uint256) {
        return balance;
    }

    //adds an account
    function addAccount(string memory _name, uint256 _balance) public {
        accounts.push(Accounts(_name, _balance));
        nameToBalance[_name] = _balance;
    }
}
```

**Comment by joeytheass** [comment]
The port was correct as 7545 however, adding that gas price line did fix it! Thanks!
