### ISSUE TITLE
During install web3 package I occur unsolvable problem

### ISSUE THREAD

**Issue by kacperte** [smartcontractkit/full-blockchain-solidity-course-py#760]
I am lack of patience for this problem. I try to install web3 package for python. Every time I have tried to do this, I occur above issue.

```
ERROR: Command errored out with exit status 1:
   command: 'c:\users\kacpe\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kacpe\\AppData\\Local\\Temp\\pip-install-1b8hkvzx\\lru-dict_3fcca7cc367c4300b9aabe9030e66f5f\\setup.py'"'"'; __file__='"'"'C:\\Users\\kacpe\\AppData\\Local\\Temp\\pip-install-1b8hkvzx\\lru-dict_3fcca7cc367c4300b9aabe9030e66f5f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\kacpe\AppData\Local\Temp\pip-wheel-1wp32ebv'
       cwd: C:\Users\kacpe\AppData\Local\Temp\pip-install-1b8hkvzx\lru-dict_3fcca7cc367c4300b9aabe9030e66f5f\
  Complete output (65 lines):
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\msvc.py", line 275, in _msvc14_get_vc_env
      out = subprocess.check_output(
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\subprocess.py", line 424, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\subprocess.py", line 528, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command 'cmd /u /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64 && set' returned non-zero exit status 255.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\kacpe\AppData\Local\Temp\pip-install-1b8hkvzx\lru-dict_3fcca7cc367c4300b9aabe9030e66f5f\setup.py", line 6, in <module>
      setup (name = 'lru-dict',
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      return run_commands(dist)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
      dist.run_commands()
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
      _build_ext.build_ext.build_extensions(self)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial     
      self.build_extension(ext)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
      _build_ext.build_extension(self, ext)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
      objects = self.compiler.compile(sources,
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
      self.initialize()
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\msvc.py", line 280, in _msvc14_get_vc_env
      raise distutils.errors.DistutilsPlatformError(
  setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for lru-dict
  Running setup.py clean for lru-dict
  Building wheel for bitarray (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\kacpe\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kacpe\\AppData\\Local\\Temp\\pip-install-1b8hkvzx\\bitarray_aefdbe80432a43a98706ce4864c2dc80\\setup.py'"'"'; __file__='"'"'C:\\Users\\kacpe\\AppData\\Local\\Temp\\pip-install-1b8hkvzx\\bitarray_aefdbe80432a43a98706ce4864c2dc80\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\kacpe\AppData\Local\Temp\pip-wheel-ijq099mp'
       cwd: C:\Users\kacpe\AppData\Local\Temp\pip-install-1b8hkvzx\bitarray_aefdbe80432a43a98706ce4864c2dc80\
  Complete output (71 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\bitarray
  copying bitarray\test_bitarray.py -> build\lib.win-amd64-3.9\bitarray
  copying bitarray\test_util.py -> build\lib.win-amd64-3.9\bitarray
  copying bitarray\util.py -> build\lib.win-amd64-3.9\bitarray
  copying bitarray\__init__.py -> build\lib.win-amd64-3.9\bitarray
  running build_ext
  Traceback (most recent call last):
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\msvc.py", line 275, in _msvc14_get_vc_env
      out = subprocess.check_output(
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\subprocess.py", line 424, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\subprocess.py", line 528, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command 'cmd /u /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64 && set' returned non-zero exit status 255.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\kacpe\AppData\Local\Temp\pip-install-1b8hkvzx\bitarray_aefdbe80432a43a98706ce4864c2dc80\setup.py", line 18, in <module>
      setup(
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      return run_commands(dist)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
      dist.run_commands()
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
      _build_ext.build_ext.build_extensions(self)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial     
      self.build_extension(ext)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
      _build_ext.build_extension(self, ext)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
      objects = self.compiler.compile(sources,
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
      self.initialize()
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
    File "c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\msvc.py", line 280, in _msvc14_get_vc_env
      raise distutils.errors.DistutilsPlatformError(
  setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for bitarray
  Running setup.py clean for bitarray
  Building wheel for cytoolz (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\kacpe\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kacpe\\AppData\\Local\\Temp\\pip-install-1b8hkvzx\\cytoolz_97416e26c0be440fb7f02f80b7d7709f\\setup.py'"'"'; __file__='"'"'C:\\Users\\kacpe\\AppData\\Local\\Temp\\pip-install-1b8hkvzx\\cytoolz_97416e26c0be440fb7f02f80b7d7709f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from 
setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\kacpe\AppData\Local\Temp\pip-wheel-0453le_v'
       cwd: C:\Users\kacpe\AppData\Local\Temp\pip-install-1b8hkvzx\cytoolz_97416e26c0be440fb7f02f80b7d7709f\
  Complete output (52 lines):
  [1/5] Cythonizing cytoolz/utils.pyx
  [2/5] Cythonizing cytoolz/dicttoolz.pyx
  [3/5] Cythonizing cytoolz/functoolz.pyx
  [4/5] Cythonizing cytoolz/itertoolz.pyx
  [5/5] Cythonizing cytoolz/recipes.pyx
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\cytoolz
  copying cytoolz\compatibility.py -> build\lib.win-amd64-3.9\cytoolz
  copying cytoolz\_signatures.py -> build\lib.win-amd64-3.9\cytoolz
  copying cytoolz\_version.py -> build\lib.win-amd64-3.9\cytoolz
  copying cytoolz\__init__.py -> build\lib.win-amd64-3.9\cytoolz
  creating build\lib.win-amd64-3.9\cytoolz\curried
  copying cytoolz\curried\exceptions.py -> build\lib.win-amd64-3.9\cytoolz\curried
  copying cytoolz\curried\operator.py -> build\lib.win-amd64-3.9\cytoolz\curried
  copying cytoolz\curried\__init__.py -> build\lib.win-amd64-3.9\cytoolz\curried
  copying cytoolz\dicttoolz.pyx -> build\lib.win-amd64-3.9\cytoolz
  copying cytoolz\functoolz.pyx -> build\lib.win-amd64-3.9\cytoolz
  copying cytoolz\itertoolz.pyx -> build\lib.win-amd64-3.9\cytoolz
  copying cytoolz\recipes.pyx -> build\lib.win-amd64-3.9\cytoolz
  copying cytoolz\utils.pyx -> build\lib.win-amd64-3.9\cytoolz
  copying cytoolz\cpython.pxd -> build\lib.win-amd64-3.9\cytoolz
  copying cytoolz\dicttoolz.pxd -> build\lib.win-amd64-3.9\cytoolz
  copying cytoolz\functoolz.pxd -> build\lib.win-amd64-3.9\cytoolz
  copying cytoolz\itertoolz.pxd -> build\lib.win-amd64-3.9\cytoolz
  copying cytoolz\recipes.pxd -> build\lib.win-amd64-3.9\cytoolz
  copying cytoolz\utils.pxd -> build\lib.win-amd64-3.9\cytoolz
  copying cytoolz\__init__.pxd -> build\lib.win-amd64-3.9\cytoolz
  creating build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\dev_skip_test.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_compatibility.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_curried.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_dicttoolz.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_docstrings.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_doctests.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_functoolz.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_inspect_args.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_itertoolz.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_none_safe.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_recipes.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_serialization.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_signatures.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_tlz.py -> build\lib.win-amd64-3.9\cytoolz\tests
  copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.9\cytoolz\tests
  running build_ext
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for cytoolz
  Running setup.py clean for cytoolz
Failed to build lru-dict bitarray cytoolz
Installing collected packages: cytoolz, eth-utils, varint, rlp, pycryptodome, parsimonious, netaddr, multidict, hexbytes, frozenlist, eth-keys, base58, yarl, multiaddr, 
eth-rlp, eth-keyfile, eth-abi, charset-normalizer, bitarray, async-timeout, aiosignal, websockets, lru-dict, ipfshttpclient, eth-account, aiohttp
    Running setup.py install for cytoolz ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\kacpe\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kacpe\\AppData\\Local\\Temp\\pip-install-1b8hkvzx\\cytoolz_97416e26c0be440fb7f02f80b7d7709f\\setup.py'"'"'; __file__='"'"'C:\\Users\\kacpe\\AppData\\Local\\Temp\\pip-install-1b8hkvzx\\cytoolz_97416e26c0be440fb7f02f80b7d7709f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 
'C:\Users\kacpe\AppData\Local\Temp\pip-record-j4h7_gap\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kacpe\appdata\local\programs\python\python39\Include\cytoolz'
         cwd: C:\Users\kacpe\AppData\Local\Temp\pip-install-1b8hkvzx\cytoolz_97416e26c0be440fb7f02f80b7d7709f\
    Complete output (54 lines):
    [1/5] Cythonizing cytoolz/utils.pyx
    [2/5] Cythonizing cytoolz/dicttoolz.pyx
    [3/5] Cythonizing cytoolz/functoolz.pyx
    [4/5] Cythonizing cytoolz/itertoolz.pyx
    [5/5] Cythonizing cytoolz/recipes.pyx
    running install
    c:\users\kacpe\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\_version.py -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\__init__.py -> build\lib.win-amd64-3.9\cytoolz
    creating build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win-amd64-3.9\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win-amd64-3.9\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win-amd64-3.9\cytoolz
    creating build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win-amd64-3.9\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.9\cytoolz\tests
    running build_ext
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\kacpe\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kacpe\\AppData\\Local\\Temp\\pip-install-1b8hkvzx\\cytoolz_97416e26c0be440fb7f02f80b7d7709f\\setup.py'"'"'; __file__='"'"'C:\\Users\\kacpe\\AppData\\Local\\Temp\\pip-install-1b8hkvzx\\cytoolz_97416e26c0be440fb7f02f80b7d7709f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\kacpe\AppData\Local\Temp\pip-record-j4h7_gap\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kacpe\appdata\local\programs\python\python39\Include\cytoolz' Check the logs for full command output.
```

What I already done:

Pip upgrade
Uninstall Microsoft Visual C++ from widnows
Install Microsoft Visual C++ 14.0 from official site (Microsoft C++ Build Tools) and then uninstall and install again,
Try to install this at Python 3.9 and 3.10
System Windows 10
Of course when i install web3 without dependencies everything is ok, but this is not acceptable for project i want to do.

Do you have any idea what can fix this?

**Comment by cromewar** [comment]
Hello @kacperte does [this](https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/118#discussioncomment-1843933) make any sense to you? (Csalle solution)

Also you can try one of these:

1. install visual studio community and it's python developments tools.
2. Use WSL for web3 development (recommended)

**Comment by kubesqrt** [comment]
Hey! I had a similar issue before. First of all the package is not compatible with python10 just yet. what you need to do is install the .whl yourself manually. from this link: https://www.lfd.uci.edu/~gohlke/pythonlibs/#bitarray . The cp version is the version of python it is compatible with.  The one it seems in the error is "cytoolz" although there may be others. 

**I wouldnt recommend this method though.**

What you should do is download VirtualBox and install linux on it. Then just code from there. It is much smoother doing everything in linux. If you have any issues dm me.

Dzienki :)

**Comment by cromewar** [comment]
Yep @kubesqrt python 3.10.1 has problems with web3 libraries, wsl is an alternative to virtual box.

**Comment by oliveruf42** [comment]
I had the same problem. Some of packages for the class started clashing with ones already installed. In the terminal try ```pip install cython``` ```pip install cytoolz``` For brownie if you get an error about user access 
try ```sudo pip install eth-brownie```
Try using a vitrtualenv with Python3.First set up a directory to work with-in the terminal type```$ mkdir python-virtual-environments && cd python-virtual-environments```In the terminal type```$ python3 -m venv env```  for Mac
Here's the link with info on setting up virtualenv. This way you don't have to install all the packages globally.
```https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment```
Hope this helps good luck

**Comment by david-randoll** [comment]
> 

Thank you! this worked for me

**Comment by david-randoll** [comment]
> Hello @kacperte does [this](https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/118#discussioncomment-1843933) make any sense to you? (Csalle solution)
> 
> Also you can try one of these:
> 
> 1. install visual studio community and it's python developments tools.
> 2. Use WSL for web3 development (recommended)

Clicking the link and following the solution posted by [CSalle](https://github.com/CSalle) worked for me.
