### ISSUE TITLE
Lesson 4: solcx.exceptions.SolcInstallationError: Downloaded binary would not execute

### ISSUE THREAD

**Issue by mcjohnson1** [smartcontractkit/full-blockchain-solidity-course-py#985]
Hello all,

I'm running into an error when trying to compile the `SimpleStorage.sol` code in `deploy.py`. Here is what my code currently looks like 
`from solcx import compile_standard, install_solc

install_solc("0.6.0")

with open("./SimpleStorage.sol", "r") as file:
    simple_storage_file = file.read()

compiled_sol = compile_standard(
    {
        "language": "Solidity",
        "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
        "settings": {
            "outputSelection": {
                "*": {"*": ["abi", "metadata", "evm.bytecode", "evm.sourceMap"]}
            }
        },
    },
    solc_version="0.6.0",
)

print(compiled_sol)
`
Running `python3 deploy.py` leads to the following error and stacktrace: 
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/solcx/install.py", line 633, in _validate_installation
    installed_version = wrapper._get_solc_version(binary_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/solcx/wrapper.py", line 17, in _get_solc_version
    stdout_data = subprocess.check_output([str(solc_binary), "--version"], encoding="utf8")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 86] Bad CPU type in executable: '/Users/mattjohnson/.solcx/solc-v0.6.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mattjohnson/demos/blockchain-solidity-course-py/web3_py_simple_storage/deploy.py", line 3, in <module>
    install_solc("0.6.0")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/solcx/install.py", line 466, in install_solc
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/solcx/install.py", line 459, in install_solc
    _validate_installation(version, solcx_binary_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/solcx/install.py", line 636, in _validate_installation
    raise SolcInstallationError(
solcx.exceptions.SolcInstallationError: Downloaded binary would not execute, or returned unexpected output. If this issue persists, you can try to compile from source code using 'solcx.compile_solc('0.6.0')'.`

Any advice on how to fix this compilation issue would be greatly appreciated. Thanks!

**Comment by mcjohnson1** [comment]
Appreciate the reply. I just gave your suggestion a go, and received the same error. Not sure this will give any further insight, but this is my `SimpleStorage.sol` file -
```
// SPDX-License-Identifier: MIT

pragma solidity >=0.6.0 <0.9.0;

contract SimpleStorage {
    uint256 favoriteNumber;

    // This is a comment!
    struct People {
        uint256 favoriteNumber;
        string name;
    }

    People[] public people;
    mapping(string => uint256) public nameToFavoriteNumber;

    function store(uint256 _favoriteNumber) public {
        favoriteNumber = _favoriteNumber;
    }

    function retrieve() public view returns (uint256) {
        return favoriteNumber;
    }

    function addPerson(string memory _name, uint256 _favoriteNumber) public {
        people.push(People(_favoriteNumber, _name));
        nameToFavoriteNumber[_name] = _favoriteNumber;
    }
}
```

**Comment by mcjohnson1** [comment]
@bot-eth-dev Yep, tried that. Same error unfortunately.

**Comment by mcjohnson1** [comment]
Haha yes I did :) ... Wish that wasn't the case, would've been an easy fix then. Also, I'd be getting an import error right away when trying to import `solcx` if I hadn't installed the package.

**Comment by mcjohnson1** [comment]
My concern is there's a compatibility issue with macOS 12.0.1. Or, maybe an underlying issue that isn't properly being conveyed through the error handling

**Comment by mcjohnson1** [comment]
Thanks! Here's a potentially related issue that someone was running into with brownie - https://github.com/eth-brownie/brownie/issues/1086

I will give installing through brew a try if there aren't any other obvious suggestions. I've just been holding off because I don't want too many python installations floating around

**Comment by mcjohnson1** [comment]
The interpreter I'm using is 3.9 - /Library/Frameworks/Python.framework/Versions/3.9/bin/python3

The solcx installation location - /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/solcx/install.py

**Comment by mcjohnson1** [comment]
Good suggestion... So I'd originally started out using python's latest release, which is 3.10.2. That didn't work, but I saw there wasn't much support for python 3.10 in the web3 related packages. I then switched to 3.9 since that's was what was used in the video. Since obviously that didn't work, I tested out your suggestion of trying out 3.8.x. I ended up choosing their latest release with binary installation: 3.8.10. What's interesting about this release as well, is they have a binary installation with this description: "experimental, for macOS 11 Big Sur and later; recommended on Apple Silicon". None of the other newer python releases had this description for any of their installers (ie 3.10.x and 3.9.x). I happen to be using one of Apple's new M1 Pro chips. Anyways, this latest installation ended up working. Thank you so much for the help and working through this with me!

**Comment by mcjohnson1** [comment]
Closing this issue since it has been resolved.
